services:
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - database

  database:
    image: mariadb:11.4
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
